#!/usr/bin/env node
// Regenerates sources.md from the data files (all links, grouped by stage and view).
// Usage: node tools/build-sources.js
const fs = require("fs"), path = require("path");
const ROOT = path.join(__dirname, "..");
const PAI = require("./load-data")(ROOT);
const linkRe = /\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g;
function collect(obj, out, label) {
  if (typeof obj === "string") { let m; while ((m = linkRe.exec(obj))) out.set(m[2], out.get(m[2]) || m[1]); return; }
  if (Array.isArray(obj)) return obj.forEach(x => collect(x, out, label));
  if (obj && typeof obj === "object") {
    if (obj.url && (obj.title || obj.t)) out.set(obj.url, obj.title || obj.t);
    if (obj.u && obj.t) out.set(obj.u, obj.t);
    if (obj.link && obj.name) out.set(obj.link, obj.name + (obj.version ? " — " + obj.version : ""));
    Object.keys(obj).forEach(k => collect(obj[k], out, label));
  }
}
let md = `# Sources\n\nGenerated by \`node tools/build-sources.js\` from the data files on ${PAI.meta.last_verified} (site v${PAI.meta.version}).\nEvery external link used on the site, grouped by stage and view. Links were found during the October 2026 research pass; release dates were checked on official release pages or PyPI.\n\n`;
let total = 0; const all = new Set();
PAI.meta.stages.forEach(sm => {
  const out = new Map(); collect(PAI.stages[sm.id], out);
  md += `## Stage ${sm.num} — ${sm.title}\n\n`;
  [...out.entries()].sort((a, b) => a[1].localeCompare(b[1])).forEach(([u, t]) => { md += `- [${t.replace(/[\[\]]/g, "")}](${u})\n`; all.add(u); });
  md += "\n"; total += out.size;
});
[["frontier", "Frontier scan"], ["views", "Integration views (paradigms, architectures, runtime)"], ["glossary", "Glossary"], ["roadmap", "Learning roadmap"], ["capstone", "Capstone self-test"]].forEach(([k, title]) => {
  const out = new Map(); collect(PAI.data[k], out); if (!out.size) return;
  md += `## ${title}\n\n`;
  [...out.entries()].sort((a, b) => a[1].localeCompare(b[1])).forEach(([u, t]) => { md += `- [${t.replace(/[\[\]]/g, "")}](${u})\n`; all.add(u); });
  md += "\n";
});
md += `## Additional sources used in integration-view pages (HTML)\n\n- [World-Action Models for Robot Learning and Control: A Survey](https://arxiv.org/abs/2609.16074v1)\n- [awesome-wam-2026 taxonomy](https://github.com/XuejiFang/awesome-wam-2026)\n\n`;
md += `---\n${all.size} unique external URLs.\n`;
fs.writeFileSync(path.join(ROOT, "sources.md"), md);
console.log("sources.md written:", all.size, "unique URLs");
